language: node_js
node_js:
  - "10"
cache: npm
script:
  - npm run transpile
deploy:
  provider: npm
  skip_cleanup: true
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
