language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: npm
script:
  - npm run transpile
before_deploy:
  # Set up git user name and tag this commit
  - echo "testing 1, 2, 3"
  # - echo $GIT_USER_NAME
  # - echo $GIT_EMAIL
  # - git config --local user.name $GIT_USER_NAME
  # - git config --local user.email $GIT_EMAIL
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  # - git tag $TRAVIS_TAG
deploy:
  # - provider: releases
  #   api_key: $GITHUB_KEY
  #   file: "README.md"
  #   skip_cleanup: true
  #   on:
  #     tags: true
  - provider: npm
    email: $EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
