language: node_js
node_js:
  - "10"
branches:
  only:
    - master
# cache: npm
script:
  - npm run prepublishOnly
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GIT_USER_NAME
  - git config --local user.email $GIT_EMAIL
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export TRAVIS_TAG=v$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    skip_cleanup: true
    on:
      branch: master
  # - provider: npm
  #   email: $EMAIL
  #   api_key: $NPM_TOKEN
  #   on:
  #     branch: master
