language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: npm
script:
  - npm run transpile
# before_deploy:
#   - git config --local user.name $GIT_USER_NAME
#   - git config --local user.email $GIT_EMAIL
#   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#   - git tag $TRAVIS_TAG
# deploy:
#   provider: npm
#   skip_cleanup: true
#   email: $EMAIL
#   api_key: $NPM_TOKEN
#   on:
#     branch: master
#     tags: true
