language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: npm
script:
  - npm run transpile
deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    file: "README.md"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: $EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
